### ISSUE TITLE
Missing Realm constructor

### ISSUE THREAD

**Issue by Hatko** [realm/realm-js#1340]
## Goals

I'm trying to include realm into my existing react-native app

## Expected Results

Run my project in iOS via Expo app, as before realm installation

## Actual Results

I have **Missing Realm constructor** error.

<img width="412" alt="screen shot 2017-09-24 at 14 23 47" src="https://user-images.githubusercontent.com/6848723/30783150-76ce94d0-a13e-11e7-9376-bf915ccedb6a.png">

I've tried to run 
⇒  react-native link realm

output is
Scanning 794 folders for symlinks in pathToProject/node_modules (8ms)

After this step problem is still here

## Steps to Reproduce

1) Add realm to project
2) npm start

## Code Sample

Problem reproduces for me if I have import of realm in my code
`import Realm from 'realm'`

## Version of Realm and Tooling

- Realm JS SDK Version: ^1.12.0, react-native-cli: 2.0.1, react-native: 0.47.2
- Node or React Native: React Native
- Client OS & Version: macOS Sierra 10.12.6
- Which debugger for React Native: None

**Comment by Hatko** [comment]
I've tried to update react-native to 0.48.4

Also, I created an empty project and included Realm inside - get the same error.

**Comment by cherednichenkoa** [comment]
I have the same error

**Comment by TGPSKI** [comment]
Same here for prod users on iOS

https://github.com/realm/realm-js/issues/1230#issuecomment-332379266

**Comment by kneth** [comment]
We have just released 1.13.0. Please try to upgrade.

**Comment by TGPSKI** [comment]
@kneth Thank you so much!!!

**Comment by Hatko** [comment]
@kneth, unfortunately we still getting the same error. steps to reproduce are really straightforward:

1) npm install --save realm
2) run with expo xde on iPhone simulator
3) error, saying missing constructor
4) react-native link realm
5) error, saying missing constructor

can you reproduce this issue? ver in package.json:     "realm": "^1.13.0",

**Comment by ashwinphatak** [comment]
@Hatko I see that you're using Expo. Have you detached the project?

Without detaching, Expo doesn't support custom native modules.

https://docs.expo.io/versions/latest/guides/detach.html

> If you created an Expo project in XDE and you want a way to add custom native modules, this guide will explain how to use ExpoKit for that purpose.
> 
> Normally, Expo apps are written in pure JS and never “drop down” to the native iOS or Android layer. This is core to the Expo philosophy and it’s part of what makes Expo fast and powerful to use.
> 
> However, there are some cases where advanced developers need native capabilities outside of what Expo offers out-of-the-box. The most common situation is when a project requires a specific Native Module which is not supported by React Native Core or the Expo SDK.

Also see https://github.com/ashwinphatak/realmexpo/commits/master

The steps I followed to get Realm working were:
1) exp detach
2) react-native link
3) Run the app using Expo XDE

**Comment by Hatko** [comment]
You made it clear now, thank you! 🙂
