### ISSUE TITLE
New Project which doesn't use  Realm throws Missing Realm constructor. Did you run "react-native link realm"? 

### ISSUE THREAD

**Issue by Aravindhan12** [realm/realm-js#1630]
I have installed & linked Realm for a Project. I have been working in Realm without any issues. But, Now I have created a new react native project with command react-native init project name and started the app in android and it throws Missing Realm constructor. Did you run "react-native link realm"? 

I don't understand why this error occurs as I'm not using  Realm in this newly created project.

Can anyone help me to get rid of this error?

**Comment by kneth** [comment]
I think this is better asked at StackOverflow. But my guess is that one of your dependencies depend on Realm.

**Comment by Aravindhan12** [comment]
@kneth  Thanks for pointing it out. I have fixed it closing the React Packager Terminal and starting the project again as mentioned in this link https://stackoverflow.com/questions/39457855/cant-run-hello-world-react-native-app-missing-realm-constructor.

**Comment by saddaf88** [comment]
Hi
I am still getting this error in ios simulator. i have written a post in stackoverflow about it. but none reply there. can anyone help me here.. here is my stackoverflow post [https://stackoverflow.com/questions/48184934/missing-realm-constructor-react-native-ios?rq=1](url)
please help me

**Comment by bmunkholm** [comment]
@saddaf88 Please include more details in the SO question so people have a chance to help you. SO provides good guidelines for how to describe problems that I would encourage you to follow.
