### ISSUE TITLE
NetworkError: Failed to execute 'send' on 'XMLhttpRequest'...

### ISSUE THREAD

**Issue by BravenxX** [realm/realm-js#2551]
## Goals

- Open debugger whiout errors

## Actual Results

on device emulator and real device connected by usb

![image](https://user-images.githubusercontent.com/43297929/66316454-16916a80-e8ee-11e9-8d62-06e86b15c81b.png)

on browser console

![image](https://user-images.githubusercontent.com/43297929/66316697-8869b400-e8ee-11e9-9d26-1719d620fa27.png)

- react-native run-android

- debug

## Version of Realm and Tooling

- Windows 10
- Android
- "dependencies": {
    "react": "^16.10.2",
    "react-native": "^0.61.2",
    "realm": "^3.2.0",
  },

Changing node_mudules/reaml/.. localhost didn't work

**Comment by BravenxX** [comment]
Solutioned! in the command terminal run this: 

adb reverse tcp:8081 tcp:8081

adb forward tcp:8082 tcp:8082

adb forward tcp:8083 tcp:8083

**Comment by yuripinage** [comment]
I still have this error for real device, but not emulator.

**Comment by kneth** [comment]
@yuripinage Did you follow the suggestion about Chrome extensions in http://facebook.github.io/react-native/docs/debugging#debugging-on-a-device-with-chrome-developer-tools

**Comment by yuripinage** [comment]
Yeah, but actually resolved with:
adb kill-server && adb root && adb reverse tcp:8081 tcp:8081 && adb forward tcp:8082 tcp:8082 && adb forward tcp:8083 tcp:8083

And also: https://github.com/realm/realm-js/issues/578#issuecomment-314481708
But localhost:8083, instead of localhost:8082

**Comment by vikil143** [comment]
I m still facing this issue any solution i tried all above solution but not work for me

**Comment by catreedle** [comment]
I'm facing this issue again with realm 10.12.0
