### ISSUE TITLE
React Native app crashes if `onFirstOpen` exists in Realm configuration

### ISSUE THREAD

**Issue by thecoorum** [realm/realm-js#4560]
### How frequently does the bug occur?

All the time

### Description

I'm trying to populate my database with some initial data with `onFirstOpen` config, but if I'm specifying it the app crashes as soon as it called without any errors

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

```
createRealmContext({
    ...
    onFirstOpen: (realm) => {
      console.log("init realm?", realm.create);
      // Create default categories
      categories.forEach((r) => {
        realm.create(
          "Category",
          Category.create({
            ...
          })
        );
      });

      // Create currencies
      currencies.forEach((r) => {
        realm.create(
          "Currency",
          Currency.create({
            ...
          })
        );
      });
    },
  });
```

### Version

10.20.0-beta.5

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 15.0

### Build environment

Which debugger for React Native: Flipper
Expo SDK 45

**Comment by takameyer** [comment]
@thecoorum I have tried to reproduce this, but it's working fine for me.  Can you provide a sample repo that duplicates this issue?

**Comment by thecoorum** [comment]
@takameyer I'll create a repro later today and share the link when it will be ready

**Comment by PimiYvan** [comment]
I got this error; but for me the problem was inside the schema; 

` liked: { type: "bool", default: false },
 // order: { type: "int", default: 10 }, // I removed this attribute, and it work, I don't know why`

I think to solve this issue, you must check inside your schema

**Comment by takameyer** [comment]
@thecoorum Just checking in.  I am still unable to reproduce this.  Have you fixed it, or do you have a way to reproduce this?

**Comment by thecoorum** [comment]
@takameyer i was unable to test it out because of project migration to expo 45 and impossibility to finish migration to realm, still going to test this out with new rc

**Comment by tomduncalf** [comment]
@thecoorum did you have any luck with the new RC?

**Comment by thecoorum** [comment]
Hey @tomduncalf, sorry for long answer
Yeah, the issue still persists, I created a minimal repro here https://github.com/thecoorum/realm-expo-issue

**Comment by tomduncalf** [comment]
Hey @thecoorum, thanks for the repro. How do I start it? I tried `yarn` then `yarn ios` but I get a "Missing realm constructor" error

**Comment by thecoorum** [comment]
I was using EAS for building and then directly installing into sim. Then `expo start --dev-client` but as soon as I select the server the app crashes

**Comment by thecoorum** [comment]
Sure!
https://docs.expo.dev/build/setup/#1-install-the-latest-eas-cli

You can skip **Step 3** as the project already configured for EAS and on **Step 4** use `eas build --platform {{ platform }} --profile simulator`

**Comment by tomduncalf** [comment]
Is there a way I can run this locally? EAS is super slow to build!

**Comment by thecoorum** [comment]
`expo run:ios` is also working

**Comment by tomduncalf** [comment]
Thanks @thecoorum, I can confirm I see a crash with Expo. Interestingly it doesn't crash in a plain RN project.

We will need to investigate what is going on here – in the meantime, are you able to workaround the bug by manualy performing your `onFirstOpen` action when your app starts (and e.g. checking if any Category objects exist in the Realm to determine whether you need to do it)?

**Comment by tomduncalf** [comment]
Stack trace for investigation:

```
EXC_BAD_ACCESS


Thread 10 Crashed:: com.facebook.react.JavaScript
0   realmissue                    	       0x10717dde1 std::__1::__tree_node_base<void*>*& std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiVal>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiVal> > > > >, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiVal>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiVal> > > > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiVal>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiVal> > > > > > >::__find_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::__tree_end_node<std::__1::__tree_node_base<void*>*>*&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 17
1   realmissue                    	       0x10719ae91 std::__1::pair<std::__1::__tree_iterator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiVal>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiVal> > > > >, std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiVal>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiVal> > > > >, void*>*, long>, bool> std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiVal>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiVal> > > > >, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiVal>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiVal> > > > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiVal>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiVal> > > > > > >::__emplace_unique_key_args<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::piecewise_construct_t const&, std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>, std::__1::tuple<> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::piecewise_construct_t const&, std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>&&, std::__1::tuple<>&&) + 33
2   realmissue                    	       0x10719a415 realm::js::NativeAccessor<realm::js::realmjsi::Types>::default_value_for_property(realm::ObjectSchema const&, realm::Property const&) + 69
3   realmissue                    	       0x107199ae6 realm::Object realm::Object::create<realm::js::JsiVal, realm::js::NativeAccessor<realm::js::realmjsi::Types> >(realm::js::NativeAccessor<realm::js::realmjsi::Types>&, std::__1::shared_ptr<realm::Realm> const&, realm::ObjectSchema const&, realm::js::JsiVal, realm::CreatePolicy, realm::ObjKey, realm::Obj*) + 2278
4   realmissue                    	       0x1071a7fc8 realm::js::RealmClass<realm::js::realmjsi::Types>::create(realm::js::JsiEnv, realm::js::JsiObj, realm::js::Arguments<realm::js::realmjsi::Types>&, realm::js::ReturnValue<realm::js::realmjsi::Types>&) + 1496
5   realmissue                    	       0x10715e66f facebook::jsi::Value realm::js::wrap<&(realm::js::RealmClass<realm::js::realmjsi::Types>::create(realm::js::JsiEnv, realm::js::JsiObj, realm::js::Arguments<realm::js::realmjsi::Types>&, realm::js::ReturnValue<realm::js::realmjsi::Types>&))>(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) + 239
6   realmissue                    	       0x10715a59f std::__1::__function::__func<facebook::jsi::Value (*)(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long), std::__1::allocator<facebook::jsi::Value (*)(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>, facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*&&, unsigned long&&) + 31
7   realmissue                    	       0x106ee3a4c std::__1::__function::__value_func<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*&&, unsigned long&&) const + 156 (function.h:505)
8   realmissue                    	       0x106ee337f std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const + 127 (function.h:1182)
9   realmissue                    	       0x106ee2a6a facebook::jsc::JSCRuntime::createFunctionFromHostFunction(facebook::jsi::PropNameID const&, unsigned int, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>)::HostFunctionMetadata::call(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSValue*, unsigned long, OpaqueJSValue const* const*, OpaqueJSValue const**) + 954 (JSCRuntime.cpp:1166)
10  JavaScriptCore                	    0x7fff32db341a JSC::callJSNonFinalObjectCallbackObject(JSC::JSGlobalObject*, JSC::CallFrame*) + 682
11  JavaScriptCore                	    0x7fff3367753a JSC::handleHostCall(JSC::JSGlobalObject*, JSC::CallFrame*, JSC::JSValue, JSC::CallLinkInfo*) + 1178
12  JavaScriptCore                	    0x7fff3361e7e4 operationLinkCall + 164
13  ???                           	    0x4d73702046c4 ???
14  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
15  ???                           	    0x4d73702381a1 ???
16  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
17  JavaScriptCore                	    0x7fff32d0c646 vmEntryToJavaScript + 216
18  JavaScriptCore                	    0x7fff335684ed JSC::Interpreter::executeCall(JSC::JSGlobalObject*, JSC::JSObject*, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 653
19  JavaScriptCore                	    0x7fff32dc7c2a JSObjectCallAsFunction + 906
20  realmissue                    	       0x106edb9ed facebook::jsc::JSCRuntime::call(facebook::jsi::Function const&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) + 333 (JSCRuntime.cpp:1268)
21  realmissue                    	       0x10717f65a realm::js::Function<realm::js::realmjsi::Types>::call(realm::js::JsiEnv, realm::js::JsiFunc const&, unsigned long, realm::js::JsiVal const*) + 106
22  realmissue                    	       0x10717f558 realm::js::RealmClass<realm::js::realmjsi::Types>::get_realm_config(realm::js::JsiEnv, unsigned long, realm::js::JsiVal const*, realm::RealmConfig&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiVal>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiVal> > > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiVal>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiVal> > > > > > >&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiFunc>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiFunc> > > >&)::'lambda'(std::__1::shared_ptr<realm::Realm>)::operator()(std::__1::shared_ptr<realm::Realm>) const + 184
23  realmissue                    	       0x10717f41b std::__1::__function::__func<realm::js::RealmClass<realm::js::realmjsi::Types>::get_realm_config(realm::js::JsiEnv, unsigned long, realm::js::JsiVal const*, realm::RealmConfig&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiVal>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiVal> > > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiVal>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiVal> > > > > > >&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiFunc>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiFunc> > > >&)::'lambda'(std::__1::shared_ptr<realm::Realm>), std::__1::allocator<realm::js::RealmClass<realm::js::realmjsi::Types>::get_realm_config(realm::js::JsiEnv, unsigned long, realm::js::JsiVal const*, realm::RealmConfig&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiVal>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiVal> > > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiVal>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiVal> > > > > > >&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiFunc>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiFunc> > > >&)::'lambda'(std::__1::shared_ptr<realm::Realm>)>, void (std::__1::shared_ptr<realm::Realm>)>::operator()(std::__1::shared_ptr<realm::Realm>&&) + 43
24  realmissue                    	       0x1072d4aae realm::Realm::update_schema(realm::Schema, unsigned long long, std::__1::function<void (std::__1::shared_ptr<realm::Realm>, std::__1::shared_ptr<realm::Realm>, realm::Schema&)>, std::__1::function<void (std::__1::shared_ptr<realm::Realm>)>, bool) + 1454
25  realmissue                    	       0x10726caf0 realm::_impl::RealmCoordinator::do_get_realm(realm::RealmConfig, std::__1::shared_ptr<realm::Realm>&, realm::util::Optional<realm::VersionID>, realm::util::CheckedUniqueLock&) + 2128
26  realmissue                    	       0x10726c0f9 realm::_impl::RealmCoordinator::get_realm(realm::RealmConfig, realm::util::Optional<realm::VersionID>) + 489
27  realmissue                    	       0x1072d3897 realm::Realm::get_shared_realm(realm::RealmConfig) + 135
28  realmissue                    	       0x1071ae4b9 realm::js::RealmClass<realm::js::realmjsi::Types>::create_shared_realm(realm::js::JsiEnv, realm::RealmConfig, bool, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiVal>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiVal> > > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiVal>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiVal> > > > > > >&&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiFunc>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiFunc> > > >&&) + 249
29  realmissue                    	       0x10715aae9 realm::js::RealmClass<realm::js::realmjsi::Types>::constructor(realm::js::JsiEnv, realm::js::JsiObj, realm::js::Arguments<realm::js::realmjsi::Types>&) + 345
30  realmissue                    	       0x1071ae73c realm::js::realmjsi::ObjectWrap<realm::js::RealmClass<realm::js::realmjsi::Types> >::create_constructor(realm::js::JsiEnv)::'lambda'(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const + 252
31  realmissue                    	       0x1071ae5f8 std::__1::__function::__func<realm::js::realmjsi::ObjectWrap<realm::js::RealmClass<realm::js::realmjsi::Types> >::create_constructor(realm::js::JsiEnv)::'lambda'(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long), std::__1::allocator<realm::js::realmjsi::ObjectWrap<realm::js::RealmClass<realm::js::realmjsi::Types> >::create_constructor(realm::js::JsiEnv)::'lambda'(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>, facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*&&, unsigned long&&) + 24
32  realmissue                    	       0x106ee3a4c std::__1::__function::__value_func<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*&&, unsigned long&&) const + 156 (function.h:505)
33  realmissue                    	       0x106ee337f std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const + 127 (function.h:1182)
34  realmissue                    	       0x106ee2a6a facebook::jsc::JSCRuntime::createFunctionFromHostFunction(facebook::jsi::PropNameID const&, unsigned int, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>)::HostFunctionMetadata::call(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSValue*, unsigned long, OpaqueJSValue const* const*, OpaqueJSValue const**) + 954 (JSCRuntime.cpp:1166)
35  JavaScriptCore                	    0x7fff32db341a JSC::callJSNonFinalObjectCallbackObject(JSC::JSGlobalObject*, JSC::CallFrame*) + 682
36  JavaScriptCore                	    0x7fff3367753a JSC::handleHostCall(JSC::JSGlobalObject*, JSC::CallFrame*, JSC::JSValue, JSC::CallLinkInfo*) + 1178
37  JavaScriptCore                	    0x7fff3361e7e4 operationLinkCall + 164
38  ???                           	    0x4d73702046c4 ???
39  JavaScriptCore                	    0x7fff32d2a808 llint_entry + 122811
40  JavaScriptCore                	    0x7fff32d2a394 llint_entry + 121671
41  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
42  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
43  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
44  JavaScriptCore                	    0x7fff32d298d0 llint_entry + 118915
45  JavaScriptCore                	    0x7fff32d298d0 llint_entry + 118915
46  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
47  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
48  JavaScriptCore                	    0x7fff32d298d0 llint_entry + 118915
49  JavaScriptCore                	    0x7fff32d298d0 llint_entry + 118915
50  JavaScriptCore                	    0x7fff32d2a31d llint_entry + 121552
51  JavaScriptCore                	    0x7fff32d2a808 llint_entry + 122811
52  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
53  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
54  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
55  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
56  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
57  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
58  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
59  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
60  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
61  JavaScriptCore                	    0x7fff32d0c646 vmEntryToJavaScript + 216
62  JavaScriptCore                	    0x7fff335684ed JSC::Interpreter::executeCall(JSC::JSGlobalObject*, JSC::JSObject*, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 653
63  JavaScriptCore                	    0x7fff3391481d JSC::boundThisNoArgsFunctionCall(JSC::JSGlobalObject*, JSC::CallFrame*) + 813
64  ???                           	    0x4d7370206c77 ???
65  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
66  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
67  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
68  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
69  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
70  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
71  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
72  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
73  JavaScriptCore                	    0x7fff32d2a808 llint_entry + 122811
74  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
75  JavaScriptCore                	    0x7fff32d298d0 llint_entry + 118915
76  JavaScriptCore                	    0x7fff32d29947 llint_entry + 119034
77  JavaScriptCore                	    0x7fff32d0c646 vmEntryToJavaScript + 216
78  JavaScriptCore                	    0x7fff335684ed JSC::Interpreter::executeCall(JSC::JSGlobalObject*, JSC::JSObject*, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 653
79  JavaScriptCore                	    0x7fff3391481d JSC::boundThisNoArgsFunctionCall(JSC::JSGlobalObject*, JSC::CallFrame*) + 813
80  JavaScriptCore                	    0x7fff32d0c798 vmEntryToNative + 226
81  JavaScriptCore                	    0x7fff33568521 JSC::Interpreter::executeCall(JSC::JSGlobalObject*, JSC::JSObject*, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 705
82  JavaScriptCore                	    0x7fff32dc7c2a JSObjectCallAsFunction + 906
83  realmissue                    	       0x106edb9ed facebook::jsc::JSCRuntime::call(facebook::jsi::Function const&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) + 333 (JSCRuntime.cpp:1268)
84  realmissue                    	       0x106b31068 facebook::jsi::Function::call(facebook::jsi::Runtime&, facebook::jsi::Value const*, unsigned long) const + 104 (jsi-inl.h:228)
85  realmissue                    	       0x106b30fe5 facebook::jsi::Function::call(facebook::jsi::Runtime&, std::initializer_list<facebook::jsi::Value>) const + 101 (jsi-inl.h:233)
86  realmissue                    	       0x106f0a81a facebook::jsi::Value facebook::jsi::Function::call<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, facebook::jsi::Value>(facebook::jsi::Runtime&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, facebook::jsi::Value&&) const + 362 (jsi-inl.h:241)
87  realmissue                    	       0x106f0a639 facebook::react::JSIExecutor::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, folly::dynamic const&)::$_5::operator()() const + 153 (JSIExecutor.cpp:256)
88  realmissue                    	       0x106f0a585 decltype(static_cast<facebook::react::JSIExecutor::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, folly::dynamic const&)::$_5&>(fp)()) std::__1::__invoke<facebook::react::JSIExecutor::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, folly::dynamic const&)::$_5&>(facebook::react::JSIExecutor::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, folly::dynamic const&)::$_5&) + 21 (type_traits:3918)
89  realmissue                    	       0x106f0a53d void std::__1::__invoke_void_return_wrapper<void, true>::__call<facebook::react::JSIExecutor::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, folly::dynamic const&)::$_5&>(facebook::react::JSIExecutor::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, folly::dynamic const&)::$_5&) + 29 (invoke.h:61)
90  realmissue                    	       0x106f0a50d std::__1::__function::__alloc_func<facebook::react::JSIExecutor::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, folly::dynamic const&)::$_5, std::__1::allocator<facebook::react::JSIExecutor::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, folly::dynamic const&)::$_5>, void ()>::operator()() + 29 (function.h:178)
91  realmissue                    	       0x106f09449 std::__1::__function::__func<facebook::react::JSIExecutor::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, folly::dynamic const&)::$_5, std::__1::allocator<facebook::react::JSIExecutor::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, folly::dynamic const&)::$_5>, void ()>::operator()() + 25 (function.h:352)
92  realmissue                    	       0x106f46532 std::__1::__function::__value_func<void ()>::operator()() const + 50 (function.h:505)
93  realmissue                    	       0x106f46465 std::__1::function<void ()>::operator()() const + 21 (function.h:1182)
94  realmissue                    	       0x106c55de5 facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>) + 21 (JSIExecutor.h:107)
95  realmissue                    	       0x106c58517 decltype(static_cast<void (*&>(fp)(static_cast<std::__1::function<void ()> const&>(fp0), static_cast<std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>>(fp0))) std::__1::__invoke<void (*&)(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>), std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()> >(void (*&)(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>), std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>&&) + 87 (type_traits:3918)
96  realmissue                    	       0x106c58497 void std::__1::__invoke_void_return_wrapper<void, true>::__call<void (*&)(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>), std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()> >(void (*&)(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>), std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>&&) + 71 (invoke.h:61)
97  realmissue                    	       0x106c58427 std::__1::__function::__alloc_func<void (*)(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>), std::__1::allocator<void (*)(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)>, void (std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)>::operator()(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>&&) + 71 (function.h:178)
98  realmissue                    	       0x106c57006 std::__1::__function::__func<void (*)(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>), std::__1::allocator<void (*)(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)>, void (std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)>::operator()(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>&&) + 70 (function.h:352)
99  realmissue                    	       0x106f08a6f std::__1::__function::__value_func<void (std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)>::operator()(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>&&) const + 95 (function.h:505)
100 realmissue                    	       0x106ef9752 std::__1::function<void (std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)>::operator()(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>) const + 66 (function.h:1182)
101 realmissue                    	       0x106ef9369 facebook::react::JSIExecutor::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, folly::dynamic const&) + 457 (JSIExecutor.cpp:254)
102 realmissue                    	       0x106ec35e2 facebook::react::NativeToJsBridge::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, folly::dynamic&&)::$_2::operator()(facebook::react::JSExecutor*) const + 706 (NativeToJsBridge.cpp:207)
103 realmissue                    	       0x106ec3300 decltype(static_cast<facebook::react::NativeToJsBridge::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, folly::dynamic&&)::$_2&>(fp)(static_cast<facebook::react::JSExecutor*>(fp0))) std::__1::__invoke<facebook::react::NativeToJsBridge::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, folly::dynamic&&)::$_2&, facebook::react::JSExecutor*>(facebook::react::NativeToJsBridge::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, folly::dynamic&&)::$_2&, facebook::react::JSExecutor*&&) + 32 (type_traits:3918)
104 realmissue                    	       0x106ec32b2 void std::__1::__invoke_void_return_wrapper<void, true>::__call<facebook::react::NativeToJsBridge::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, folly::dynamic&&)::$_2&, facebook::react::JSExecutor*>(facebook::react::NativeToJsBridge::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, folly::dynamic&&)::$_2&, facebook::react::JSExecutor*&&) + 50 (invoke.h:61)
105 realmissue                    	       0x106ec3272 std::__1::__function::__alloc_func<facebook::react::NativeToJsBridge::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, folly::dynamic&&)::$_2, std::__1::allocator<facebook::react::NativeToJsBridge::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, folly::dynamic&&)::$_2>, void (facebook::react::JSExecutor*)>::operator()(facebook::react::JSExecutor*&&) + 50 (function.h:178)
106 realmissue                    	       0x106ec1f31 std::__1::__function::__func<facebook::react::NativeToJsBridge::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, folly::dynamic&&)::$_2, std::__1::allocator<facebook::react::NativeToJsBridge::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, folly::dynamic&&)::$_2>, void (facebook::react::JSExecutor*)>::operator()(facebook::react::JSExecutor*&&) + 49 (function.h:352)
107 realmissue                    	       0x106ece72a std::__1::__function::__value_func<void (facebook::react::JSExecutor*)>::operator()(facebook::react::JSExecutor*&&) const + 74 (function.h:505)
108 realmissue                    	       0x106ece6ad std::__1::function<void (facebook::react::JSExecutor*)>::operator()(facebook::react::JSExecutor*) const + 45 (function.h:1182)
109 realmissue                    	       0x106ece677 facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8::operator()() const + 87 (NativeToJsBridge.cpp:310)
110 realmissue                    	       0x106ece605 decltype(static_cast<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8&>(fp)()) std::__1::__invoke<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8&>(facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8&) + 21 (type_traits:3918)
111 realmissue                    	       0x106ece5bd void std::__1::__invoke_void_return_wrapper<void, true>::__call<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8&>(facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8&) + 29 (invoke.h:61)
112 realmissue                    	       0x106ece58d std::__1::__function::__alloc_func<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8, std::__1::allocator<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8>, void ()>::operator()() + 29 (function.h:178)
113 realmissue                    	       0x106ecd129 std::__1::__function::__func<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8, std::__1::allocator<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8>, void ()>::operator()() + 25 (function.h:352)
114 realmissue                    	       0x106f46532 std::__1::__function::__value_func<void ()>::operator()() const + 50 (function.h:505)
115 realmissue                    	       0x106f46465 std::__1::function<void ()>::operator()() const + 21 (function.h:1182)
116 realmissue                    	       0x106cb06c5 facebook::react::tryAndReturnError(std::__1::function<void ()> const&) + 21 (RCTCxxUtils.mm:74)
117 realmissue                    	       0x106cdf781 facebook::react::RCTMessageThread::tryFunc(std::__1::function<void ()> const&) + 33 (RCTMessageThread.mm:69)
118 realmissue                    	       0x106ce4a13 facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1::operator()() const + 83 (RCTMessageThread.mm:82)
119 realmissue                    	       0x106ce49a5 decltype(static_cast<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1&>(fp)()) std::__1::__invoke<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1&>(facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1&) + 21 (type_traits:3918)
120 realmissue                    	       0x106ce495d void std::__1::__invoke_void_return_wrapper<void, true>::__call<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1&>(facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1&) + 29 (invoke.h:61)
121 realmissue                    	       0x106ce492d std::__1::__function::__alloc_func<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1, std::__1::allocator<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1>, void ()>::operator()() + 29 (function.h:178)
122 realmissue                    	       0x106ce35c9 std::__1::__function::__func<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1, std::__1::allocator<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1>, void ()>::operator()() + 25 (function.h:352)
123 realmissue                    	       0x106f46532 std::__1::__function::__value_func<void ()>::operator()() const + 50 (function.h:505)
124 realmissue                    	       0x106f46465 std::__1::function<void ()>::operator()() const + 21 (function.h:1182)
125 realmissue                    	       0x106cdf4ea invocation function for block in facebook::react::RCTMessageThread::runAsync(std::__1::function<void ()>) + 42 (RCTMessageThread.mm:45)
126 CoreFoundation                	    0x7fff2037223d __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
127 CoreFoundation                	    0x7fff2037163b __CFRunLoopDoBlocks + 443
128 CoreFoundation                	    0x7fff2036bf56 __CFRunLoopRun + 853
129 CoreFoundation                	    0x7fff2036b704 CFRunLoopRunSpecific + 562
130 realmissue                    	       0x106c81215 +[RCTCxxBridge runRunLoop] + 949 (RCTCxxBridge.mm:335)
131 Foundation                    	    0x7fff208511a1 __NSThread__start__ + 1009
132 libsystem_pthread.dylib       	    0x7fff701cb4e1 _pthread_start + 125
133 libsystem_pthread.dylib       	    0x7fff701c6f6b thread_start + 15
```

**Comment by thecoorum** [comment]
Are there any benefits of using `onFirstOpen` over checking for categories and writing them if they are absent?

**Comment by tomduncalf** [comment]
@thecoorum `onFirstOpen` was designed to simplify the code users need to write to add their initial data, so you don't need to worry about checking if this is the first open. I don't _think_ there's anything that you can do exclusively with `onFirstOpen` vs manually implementing it, so long as you have a way to check if this is the first open or not

**Comment by kneth** [comment]
We have released v11.0.0 and we would like to know if you still observe the issue after upgrading.

**Comment by kneth** [comment]
I am closing the issue due to no reply back. Please comment and reopen the issue if needed.

**Comment by HighDeck** [comment]
Looke like the issue is stille there (at least on iOS) :/

Just created a new bare React-Native repo (no Expo) and having a ```onFirstOpen``` in the ```createContext``` config is making the app crash instantly. 
Completely uninstalling the app and installing it again without the ```onFirstOpen``` is working.
I tried to remove the ```realm.create``` in the function callback but looks like the presence of this ```onFirstOpen``` is enough to make the app crash.

Reproduction repo [here](https://github.com/HighDeck/RealmRepro-OnFirstOpen)

```
"dependencies": {
    "@realm/react": "^0.4.3",
    "react": "18.2.0",
    "react-native": "0.71.7",
    "realm": "^11.8.0"
  }
```

**Comment by KMuteteke** [comment]
> Looke like the issue is stille there (at least on iOS) :/
> 
> Just created a new bare React-Native repo (no Expo) and having a `onFirstOpen` in the `createContext` config is making the app crash instantly. Completely uninstalling the app and installing it again without the `onFirstOpen` is working. I tried to remove the `realm.create` in the function callback but looks like the presence of this `onFirstOpen` is enough to make the app crash.
> 
> Reproduction repo [here](https://github.com/HighDeck/RealmRepro-OnFirstOpen)
> 
> ```
> "dependencies": {
>     "@realm/react": "^0.4.3",
>     "react": "18.2.0",
>     "react-native": "0.71.7",
>     "realm": "^11.8.0"
>   }
> ```

I too am having this exact issue

**Comment by kneth** [comment]
@KMuteteke @HighDeck I have reopened the issue so we can investigate it.

**Comment by myou11** [comment]
Hi there, I discovered `onFirstOpen` today and am running into the same crashing using it that HighDeck is experiencing. My dependencies are the same as their repro repo

**Comment by worldlee78** [comment]
Yup, I am too. As soon as I use the realm.create method, the whole thing crashes. I've implemented a workaround, but it would be great if this functionality worked correctly. Is there any movement on this? Just wondering. You've done a great job with the library!
