### ISSUE TITLE
Compatibility with Cross-Platform Apple Sign-In

### ISSUE THREAD

**Issue by jasontlouro** [realm/realm-js#4787]
### Problem

I'm attempting to use [invertase/react-native-apple-authentication](https://github.com/invertase/react-native-apple-authentication) to support Apple Sign-in on a React Native mobile application. 

The setup docs for the above repo show that different Client IDs are used for Android and iOS versions of Apple login. On iOS, the Client ID that gets sent to Realm after successful login is the App ID - for example `com.yourdomain.yourapp`. On Android, the Client ID that gets sent to Realm is the Service ID we had to generate according to the react-native-apple-authentication docs [here](https://github.com/invertase/react-native-apple-authentication/blob/main/docs/ANDROID_EXTRA.md), for example `com.yourdomain.yourapp-webclient`. These must be distinct because Apple won't let you have an App ID and a Service ID with the same identifier.

Therefore, when you have `com.yourdomain.yourapp` set as the accepted Client ID in the Apple authentication provider on Realm, Sign in with Apple works on iOS but not Android, and vice versa when you set it to `com.yourdomain.yourapp-webclient`.

This means it's impossible to support Apple Sign-In on both iOS and Android simultaneously. It is also impossible to support Apple Sign-In on both iOS and a web application simultaneously.

### Solution

Add the option for a comma-delimited list of acceptable Client IDs in the Apple authentication provider UI, as you did for `aud` in Custom JWT, such that any of the Client IDs in the comma-delimited list are accepted by Realm.

### How important is this improvement for you?

Dealbreaker

**Comment by kneth** [comment]
@jasontlouro Thank you for the suggestion. We are aware of the short-comings of our current implementation. As much, the feature will be added to Atlas App Services and not directly to the SDK.

I keep the issue open until the implementation has been deployed on the Atlas App Services.

**Comment by jasontlouro** [comment]
@kneth Thanks for the reply. Any rough idea of when this change could be made? I've tried quite a few workarounds but nothing that works so far.

As a sidenote, could it be possible to allow the Custom Function authentication provider to return a user from one of the other auth methods? Realm doesn't allow merging different auth methods (i.e. if a user has an account with email/pass, and uses Log in with Google to log in with that email, they get a whole new account.). This is a **serious** shortcoming and causes a lot of headaches.

I tried solving this using the following method:

1. User logs in using any authentication method.
2. Call a Realm function from the logged in user that returns an encrypted token.
3. Log the user out and log them immediately back in, this time using the Custom Function authentication method and passing along the encrypted token.
4. The Custom Function decrypts the token to verify that the user is who they claim to be, checks all existing accounts with their email address (as there can be multiple from different auth providers) and returns the correct user ID.

However, this solution didn't work, because Custom Function auth wants you to return an _external ID_ that Realm then maps to a new userID. It won't let me return the user ID of an existing user. If it did, I think I could solve this annoying issue once and for all using the above method.

Any thoughts on whether this could work?

**Comment by benhindle** [comment]
Hi @kneth, @jasontlouro, any updates on this? I too, am keen on this feature.

**Comment by jasontlouro** [comment]
Haven't heard anything yet @benhindle. Would be nice to have this.

**Comment by kamilryszkowski** [comment]
Same issue here, severity also very high. @kneth any update would be appreciated! Also pinging @takameyer since he worked on a related issue #4501.

**Comment by takameyer** [comment]
@kamilryszkowski it's being planned, but I cannot say for certain when it will be completed.  The current work around is to authenticate directly through Apple and pass the JWT token to Application Services:
https://www.mongodb.com/docs/realm/sdk/react-native/examples/authenticate-users/#custom-jwt-user

**Comment by jasontlouro** [comment]
@kneth 😢

**Comment by kneth** [comment]
@jasontlouro We deployed a change to Altas App Services in March which added the compatibility with cross-platform Apple sign-in. If you experience any issues, please create a new issue.

**Comment by jasontlouro** [comment]
@kneth You didn't solve this issue; you just documented it. https://www.mongodb.com/docs/atlas/app-services/authentication/apple/

> When using Sign-in with Apple with Atlas App Services, you can configure the Apple authentication provider for either a mobile application or a web application.
 If you would like to use Sign in with Apple for both, you could set up your own manual Sign in with Apple flow for either the web or mobile app. Then, use the JWT that returns with the [Custom JWT authentication provider](https://www.mongodb.com/docs/atlas/app-services/authentication/custom-jwt/#std-label-custom-jwt-authentication). In the 
[Realm SDKs](https://www.mongodb.com/docs/realm/sdk/#std-label-realm-sdks)
, you can then link the user identities for each authentication provider to a single user.
 To use Sign in with Apple exclusively with either a web or a mobile application, choose your application type and follow this guide.

What exactly was the update deployed in March? Custom JWT was already available as an option before then.

**Comment by jasontlouro** [comment]
> @kamilryszkowski it's being planned, but I cannot say for certain when it will be completed. The current work around is to authenticate directly through Apple and pass the JWT token to Application Services: https://www.mongodb.com/docs/realm/sdk/react-native/examples/authenticate-users/#custom-jwt-user
> 
> The [JWT token is obtainable](https://github.com/invertase/react-native-apple-authentication/blob/main/typedocs/interfaces/AppleRequestResponse.md#identitytoken) using the `react-native-apple-authentication` library.

@takameyer This solution doesn't work when you're also using custom JWT to handle log in with Google on a mobile app and web app, and now you need apple auth on two mobile apps + web. Custom JWT only allows up to 3 signing keys, and I can't even get it to work with our Google login when using the signing keys instead of the JWK URI.

Throwing my hands up in the air at this point, App Services is _terrible_ for authentication, and if I could start over I'd be using Supabase. What is the best way we can support Google & Apple & email/password cross-platform authentication?
