### ISSUE TITLE
SIGABRT crash on iOS using Realm v. 11.0.0

### ISSUE THREAD

**Issue by martinpoulsen** [realm/realm-js#5076]
### How frequently does the bug occur?

Sometimes

### Description

We first saw this issue when upgrading Realm from v. 10.13.0 to 10.16.0 as reported in https://github.com/realm/realm-js/issues/4525 (there's a lot of context in this issue).

We were hoping that this issue would disappear when upgrading to Hermes + Realm v. 11 but unfortunately, the problem seems to be unaffected. We get a lot of `SIGABRT` crashes but also less frequently (as has been the case since 10.16.0) some other realm crashes - for example a `EXC_BAD_ACCESS` crash.

We have implemented this file permission trick with no effect: https://github.com/realm/realm-core/issues/5731#issuecomment-1224285742

I have pasted in a stack trace of the `SIGABRT` crash below. In the hope that it helps investigating this issue, here are a few more stack traces as they vary slightly:

[SIGABRT_event_6364c947009b4020d03c0000.txt](https://github.com/realm/realm-js/files/9939727/SIGABRT_event_6364c947009b4020d03c0000.txt)
[SIGABRT_event_6364c79a009b491fe7960000.txt](https://github.com/realm/realm-js/files/9939728/SIGABRT_event_6364c79a009b491fe7960000.txt)
[SIGABRT_event_6364c689009b401ceecf0000.txt](https://github.com/realm/realm-js/files/9939729/SIGABRT_event_6364c689009b401ceecf0000.txt)
[SIGABRT_event_6364c4af009b34bbf6fc0000.txt](https://github.com/realm/realm-js/files/9939730/SIGABRT_event_6364c4af009b34bbf6fc0000.txt)
[SIGABRT_event_6364c382009b3fdfe6140000.txt](https://github.com/realm/realm-js/files/9939731/SIGABRT_event_6364c382009b3fdfe6140000.txt)
[SIGABRT_event_6364c27c009b4ad39cad0000.txt](https://github.com/realm/realm-js/files/9939732/SIGABRT_event_6364c27c009b4ad39cad0000.txt)
[SIGABRT_event_6364c1c6009b3ad1e8e40000.txt](https://github.com/realm/realm-js/files/9939733/SIGABRT_event_6364c1c6009b3ad1e8e40000.txt)
[SIGABRT_event_6364c0c7009b3b673ebf0000.txt](https://github.com/realm/realm-js/files/9939734/SIGABRT_event_6364c0c7009b3b673ebf0000.txt)
[SIGABRT_event_6364bf2c009b3fd931a80000.txt](https://github.com/realm/realm-js/files/9939735/SIGABRT_event_6364bf2c009b3fd931a80000.txt)
[SIGABRT_event_6364bda5009b3c7793230000.txt](https://github.com/realm/realm-js/files/9939736/SIGABRT_event_6364bda5009b3c7793230000.txt)
[SIGABRT_event_6364bd47009b35dcc0dc0000.txt](https://github.com/realm/realm-js/files/9939737/SIGABRT_event_6364bd47009b35dcc0dc0000.txt)
[EXC_BAD_ACCESS_event_6364cb04009b2ec0be760000.txt](https://github.com/realm/realm-js/files/9939741/EXC_BAD_ACCESS_event_6364cb04009b2ec0be760000.txt)
[EXC_BAD_ACCESS_event_6364c02a009b3067430c0000.txt](https://github.com/realm/realm-js/files/9939742/EXC_BAD_ACCESS_event_6364c02a009b3067430c0000.txt)
[EXC_BAD_ACCESS_event_636522b0009b3c39ada30000.txt](https://github.com/realm/realm-js/files/9939743/EXC_BAD_ACCESS_event_636522b0009b3c39ada30000.txt)
[EXC_BAD_ACCESS_event_6364b0c8009b349e85b50000.txt](https://github.com/realm/realm-js/files/9939744/EXC_BAD_ACCESS_event_6364b0c8009b349e85b50000.txt)
[EXC_BAD_ACCESS_event_6364b1f5009b367fdff50000.txt](https://github.com/realm/realm-js/files/9939745/EXC_BAD_ACCESS_event_6364b1f5009b367fdff50000.txt)

RN version: 0.70.4
Realm version: 11.0.0
Hermes: yes
New architecture: no

### Stacktrace & log output

```shell
CrashReporter Key:  ee1942e78cde8fca7cb71cb34d1b763109046053
Hardware Model:     iPhone15,2
Process:            driversnote
Identifier:         com.driversnote.driversnote
Version:            4.7.0
Role:               Background
OS Version:         iOS 16.1


SIGABRT: 

0  libsystem_kernel.dylib  __pthread_kill
1  libsystem_pthread.dylib pthread_kill
2  libsystem_c.dylib       abort
3  driversnote             please_report_this_issue_in_github_realm_realm_core_v_12_9_0 (driversnote)
4  driversnote             realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) (driversnote)
5  driversnote             realm::util::terminate(char const*, char const*, long, std::initializer_list<realm::util::Printable>&&) (driversnote)
6  driversnote             void realm::util::terminate<realm::NodeHeader::WidthType, realm::NodeHeader::WidthType>(char const*, char const*, long, realm::NodeHeader::WidthType, realm::NodeHeader::WidthType) (driversnote)
7  driversnote             realm::Node::calc_byte_len(unsigned long, unsigned long) const (driversnote)
8  driversnote             realm::Node::do_copy_on_write(unsigned long) (driversnote)
9  driversnote             realm::Array::set(unsigned long, long long) (driversnote)
10 driversnote             realm::ArrayIntNull::replace_nulls_with(long long) (driversnote)
11 driversnote             realm::ArrayTimestamp::set(unsigned long, realm::Timestamp) (driversnote)
12 driversnote             realm::Obj& realm::Obj::set<realm::Timestamp>(realm::ColKey, realm::Timestamp, bool) (driversnote)
13 driversnote             void realm::Object::set_property_value_impl<realm::js::JsiVal, realm::js::NativeAccessor<realm::js::realmjsi::Types> >(realm::js::NativeAccessor<realm::js::realmjsi::Types>&, realm::Property const&, realm::js::JsiVal, realm::CreatePolicy, bool) (driversnote)
14 driversnote             realm::js::RealmObjectClass<realm::js::realmjsi::Types>::set_property(realm::js::JsiEnv, realm::js::JsiObj, realm::js::String<realm::js::realmjsi::Types> const&, realm::js::JsiVal) (driversnote)
15 driversnote             facebook::jsi::Value realm::js::wrap<&realm::js::RealmObjectClass<realm::js::realmjsi::Types>::set_property>(facebook::jsi::Runtime&, facebook::jsi::Value const&, realm::js::String<realm::js::realmjsi::Types> const&, facebook::jsi::Value const&) (driversnote)
16 driversnote             operator() (function.h:505:16)
17 hermes                  facebook::hermes::HermesRuntimeImpl::HFContext::func(void*, hermes::vm::Runtime&, hermes::vm::NativeArgs) (function.h:505:16)
18 hermes                  hermes::vm::NativeFunction::_nativeCall(hermes::vm::NativeFunction*, hermes::vm::Runtime&) (Callable.h:503:9)
19 hermes                  hermes::vm::Callable::executeCall1(hermes::vm::Handle<hermes::vm::Callable>, hermes::vm::Runtime&, hermes::vm::Handle<hermes::vm::HermesValue>, hermes::vm::HermesValue, bool) (Callable.h:249:12)
20 hermes                  hermes::vm::JSObject::putNamedWithReceiver_RJS(hermes::vm::Handle<hermes::vm::JSObject>, hermes::vm::Runtime&, hermes::vm::SymbolID, hermes::vm::Handle<hermes::vm::HermesValue>, hermes::vm::Handle<hermes::vm::HermesValue>, hermes::vm::PropOpFlags) (JSObject.cpp:1360:11)
21 hermes                  hermes::vm::CallResult<hermes::vm::HermesValue, (hermes::vm::detail::CallResultSpecialize)2> hermes::vm::Interpreter::interpretFunction<false, false>(hermes::vm::Runtime&, hermes::vm::InterpreterState&) (JSObject.h:1938:10)
22 hermes                  hermes::vm::Runtime::interpretFunctionImpl(hermes::vm::CodeBlock*) (Interpreter.cpp:836:12)
23 hermes                  hermes::vm::JSFunction::_callImpl(hermes::vm::Handle<hermes::vm::Callable>, hermes::vm::Runtime&) (Callable.cpp:1126:20)
24 hermes                  facebook::hermes::HermesRuntimeImpl::call(facebook::jsi::Function const&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) (Callable.h:249:12)
25 driversnote             call (decorator.h:303:19)
26 driversnote             realm::js::Function<realm::js::realmjsi::Types>::call(realm::js::JsiEnv, realm::js::JsiFunc const&, realm::js::JsiObj const&, unsigned long, realm::js::JsiVal const*) (driversnote)
27 driversnote             realm::js::RealmClass<realm::js::realmjsi::Types>::write(realm::js::JsiEnv, realm::js::JsiObj, realm::js::Arguments<realm::js::realmjsi::Types>&, realm::js::ReturnValue<realm::js::realmjsi::Types>&) (driversnote)
28 driversnote             facebook::jsi::Value realm::js::wrap<&realm::js::RealmClass<realm::js::realmjsi::Types>::write>(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) (driversnote)
29 driversnote             operator() (function.h:505:16)
30 hermes                  facebook::hermes::HermesRuntimeImpl::HFContext::func(void*, hermes::vm::Runtime&, hermes::vm::NativeArgs) (function.h:505:16)
31 hermes                  hermes::vm::NativeFunction::_nativeCall(hermes::vm::NativeFunction*, hermes::vm::Runtime&) (Callable.h:503:9)
32 hermes                  hermes::vm::CallResult<hermes::vm::HermesValue, (hermes::vm::detail::CallResultSpecialize)2> hermes::vm::Interpreter::interpretFunction<false, false>(hermes::vm::Runtime&, hermes::vm::InterpreterState&) (Interpreter.cpp:287:12)
33 hermes                  hermes::vm::Runtime::interpretFunctionImpl(hermes::vm::CodeBlock*) (Interpreter.cpp:836:12)
34 hermes                  hermes::vm::GeneratorInnerFunction::callInnerFunction(hermes::vm::Handle<hermes::vm::GeneratorInnerFunction>, hermes::vm::Runtime&, hermes::vm::Handle<hermes::vm::HermesValue>, hermes::vm::GeneratorInnerFunction::Action) (Callable.cpp:1126:20)
35 hermes                  hermes::vm::generatorResume(hermes::vm::Runtime&, hermes::vm::Handle<hermes::vm::GeneratorInnerFunction>, hermes::vm::Handle<hermes::vm::HermesValue>) (GeneratorPrototype.cpp:97:19)
36 hermes                  hermes::vm::NativeFunction::_nativeCall(hermes::vm::NativeFunction*, hermes::vm::Runtime&) (Callable.h:503:9)
37 hermes                  hermes::vm::CallResult<hermes::vm::HermesValue, (hermes::vm::detail::CallResultSpecialize)2> hermes::vm::Interpreter::interpretFunction<false, false>(hermes::vm::Runtime&, hermes::vm::InterpreterState&) (Interpreter.cpp:287:12)
38 hermes                  hermes::vm::Runtime::interpretFunctionImpl(hermes::vm::CodeBlock*) (Interpreter.cpp:836:12)
39 hermes                  hermes::vm::JSFunction::_callImpl(hermes::vm::Handle<hermes::vm::Callable>, hermes::vm::Runtime&) (Callable.cpp:1126:20)
40 hermes                  hermes::vm::Callable::executeCall(hermes::vm::Handle<hermes::vm::Callable>, hermes::vm::Runtime&, hermes::vm::Handle<hermes::vm::HermesValue>, hermes::vm::Handle<hermes::vm::HermesValue>, hermes::vm::Handle<hermes::vm::JSObject>) (Callable.h:249:12)
41 hermes                  hermes::vm::functionPrototypeApply(void*, hermes::vm::Runtime&, hermes::vm::NativeArgs) (Function.cpp:224:10)
42 hermes                  hermes::vm::NativeFunction::_nativeCall(hermes::vm::NativeFunction*, hermes::vm::Runtime&) (Callable.h:503:9)
43 hermes                  hermes::vm::CallResult<hermes::vm::HermesValue, (hermes::vm::detail::CallResultSpecialize)2> hermes::vm::Interpreter::interpretFunction<false, false>(hermes::vm::Runtime&, hermes::vm::InterpreterState&) (Interpreter.cpp:287:12)
44 hermes                  hermes::vm::Runtime::interpretFunctionImpl(hermes::vm::CodeBlock*) (Interpreter.cpp:836:12)
45 hermes                  hermes::vm::JSFunction::_callImpl(hermes::vm::Handle<hermes::vm::Callable>, hermes::vm::Runtime&) (Callable.cpp:1126:20)
46 hermes                  hermes::vm::BoundFunction::_boundCall(hermes::vm::BoundFunction*, hermes::inst::Inst const*, hermes::vm::Runtime&) (Callable.h:249:12)
47 hermes                  hermes::vm::CallResult<hermes::vm::HermesValue, (hermes::vm::detail::CallResultSpecialize)2> hermes::vm::Interpreter::interpretFunction<false, false>(hermes::vm::Runtime&, hermes::vm::InterpreterState&) (Interpreter.cpp:291:12)
48 hermes                  hermes::vm::Runtime::interpretFunctionImpl(hermes::vm::CodeBlock*) (Interpreter.cpp:836:12)
49 hermes                  hermes::vm::JSFunction::_callImpl(hermes::vm::Handle<hermes::vm::Callable>, hermes::vm::Runtime&) (Callable.cpp:1126:20)
50 hermes                  hermes::vm::BoundFunction::_boundCall(hermes::vm::BoundFunction*, hermes::inst::Inst const*, hermes::vm::Runtime&) (Callable.h:249:12)
51 hermes                  facebook::hermes::HermesRuntimeImpl::call(facebook::jsi::Function const&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) (Callable.h:249:12)
52 driversnote             call (decorator.h:303:19)
53 driversnote             call (jsi-inl.h:234:18)
54 driversnote             operator() (function.h:505:16)
55 driversnote             operator() (function.h:505:16)
56 driversnote             tryFunc (RCTMessageThread.mm:69:20)
57 driversnote             operator() (function.h:505:16)
58 CoreFoundation          <redacted>
59 CoreFoundation          <redacted>
60 CoreFoundation          <redacted>
61 CoreFoundation          CFRunLoopRunSpecific
62 driversnote             +[RCTCxxBridge runRunLoop] (RCTCxxBridge.mm:335:12)
63 Foundation              <redacted>
64 libsystem_pthread.dylib _pthread_start
```

### Can you reproduce the bug?

Not yet

### Version

11.0.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 15.x/16.x

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
@martinpoulsen Thank you for your detailed bug report. I am sorry to hear you are still experience these crashes. We are currently investigating similar instabilities across the Realm SDKs supporting iOS (https://github.com/realm/realm-core/issues/5953, https://github.com/realm/realm-core/issues/5947, https://github.com/realm/realm-core/issues/5761).

**Comment by martinpoulsen** [comment]
Thanks @kneth - good to know that you are investigating this.

How valuable would it be for the investigations to have a realm file from an affected device? As mentioned, we haven't been able to reproduce it yet, but we might decide to spend significant resources on trying to reproduce it in case it is likely to make a difference.

**Comment by nicola-cab** [comment]
Hello, thanks for reporting this. We are aware of this type of database corruptions. We have found a possible solution to the problem, and we are currently working on writing an automated test for it. There are some things we are still trying to understand, and we will release the fix once we are happy with our implementation.
This will mean that your SDK will have to be upgraded and most likely your old corrupted database file will be lost.

**Comment by Pingou** [comment]
@nicola-cab thank you for your answer. Could you give me a very rough estimate on when the patch will be available?

**Comment by nicola-cab** [comment]
@Pingou we are discussing if releasing this. So it should be very soon...

**Comment by martinpoulsen** [comment]
@nicola-cab That sounds amazing! Thanks for sharing. We've had terrible iOS app stability due to this issue for more than 6 months so we are very excited to hear that a fix is being released soon 🙌

**Comment by martinpoulsen** [comment]
@kneth @nicola-cab we are still seeing the `SIGABRT` crash after upgrading to Realm v. 11.2.0. Could this be explained by users who had their database corrupted while using a previous app version - or is it unexpected to see these crashes at this point?

Here is an example crash report:

```
CrashReporter Key:  489967ede56ceddced399cc3e8fa122c774c0858
Hardware Model:     iPhone11,2
Process:            driversnote
Identifier:         com.driversnote.driversnote
Version:            4.7.5
Role:               Background
OS Version:         iOS 16.0.2


SIGABRT: 

0  libsystem_kernel.dylib  ___pthread_kill
1  libsystem_pthread.dylib _pthread_kill
2  libsystem_c.dylib       _abort
3  driversnote             please_report_this_issue_in_github_realm_realm_core_v_12_12_0 (driversnote)
4  driversnote             realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) (driversnote)
5  driversnote             realm::util::terminate_with_info(char const*, char const*, long, char const*, std::initializer_list<realm::util::Printable>&&) (driversnote)
6  driversnote             void realm::util::terminate_with_info<unsigned long&, unsigned long>(char const*, int, char const*, char const*, unsigned long&, unsigned long&&) (driversnote)
7  driversnote             realm::StringIndex::StringIndex(unsigned long, realm::ArrayParent*, unsigned long, realm::ClusterColumn const&, realm::Allocator&) (driversnote)
8  driversnote             realm::Table::refresh_index_accessors() (driversnote)
9  driversnote             realm::Group::create_table_accessor(unsigned long) (driversnote)
10 driversnote             realm::Group::do_get_table(unsigned long) (driversnote)
11 driversnote             realm::Transaction::check_consistency() (driversnote)
12 driversnote             realm::DB::open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, realm::DBOptions const&) (driversnote)
13 driversnote             realm::DB::create(std::__1::unique_ptr<realm::Replication, std::__1::default_delete<realm::Replication> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, realm::DBOptions const&) (driversnote)
14 driversnote             realm::_impl::RealmCoordinator::open_db() (driversnote)
15 driversnote             realm::_impl::RealmCoordinator::do_get_realm(realm::RealmConfig, std::__1::shared_ptr<realm::Realm>&, std::__1::optional<realm::VersionID>, realm::util::CheckedUniqueLock&) (driversnote)
16 driversnote             realm::_impl::RealmCoordinator::get_realm(realm::RealmConfig, std::__1::optional<realm::VersionID>) (driversnote)
17 driversnote             realm::Realm::get_shared_realm(realm::RealmConfig) (driversnote)
18 driversnote             realm::js::RealmClass<realm::js::realmjsi::Types>::create_shared_realm(realm::js::JsiEnv, realm::RealmConfig, bool, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiVal>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiVal> > > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiVal>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiVal> > > > > > >&&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiFunc>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiFunc> > > >&&) (driversnote)
19 driversnote             realm::js::RealmClass<realm::js::realmjsi::Types>::constructor(realm::js::JsiEnv, realm::js::JsiObj, realm::js::Arguments<realm::js::realmjsi::Types>&) (driversnote)
20 driversnote             realm::js::realmjsi::ObjectWrap<realm::js::RealmClass<realm::js::realmjsi::Types> >::create_constructor(realm::js::JsiEnv)::{lambda(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)#1}::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const (driversnote)
21 driversnote             operator() (function.h:505:16)
22 hermes                  facebook::hermes::HermesRuntimeImpl::HFContext::func(void*, hermes::vm::Runtime&, hermes::vm::NativeArgs) (function.h:505:16)
23 hermes                  hermes::vm::NativeFunction::_nativeCall(hermes::vm::NativeFunction*, hermes::vm::Runtime&) (Callable.h:503:9)
24 HermesBuiltin.cpp       hermes::vm::hermesBuiltinApply(void*, hermes::vm::Runtime&, hermes::vm::NativeArgs)
25 hermes                  hermes::vm::NativeFunction::_nativeCall(hermes::vm::NativeFunction*, hermes::vm::Runtime&) (Callable.h:503:9)
26 hermes                  hermes::vm::Interpreter::implCallBuiltin(hermes::vm::Runtime&, hermes::vm::PinnedHermesValue*, hermes::vm::CodeBlock*, unsigned int) (Interpreter-slowpaths.cpp:326:16)
27 hermes                  hermes::vm::CallResult<hermes::vm::HermesValue, (hermes::vm::detail::CallResultSpecialize)2> hermes::vm::Interpreter::interpretFunction<false, false>(hermes::vm::Runtime&, hermes::vm::InterpreterState&) (Interpreter.cpp:1701:9)
28 hermes                  hermes::vm::Runtime::interpretFunctionImpl(hermes::vm::CodeBlock*) (Interpreter.cpp:836:12)
29 hermes                  hermes::vm::JSFunction::_callImpl(hermes::vm::Handle<hermes::vm::Callable>, hermes::vm::Runtime&) (Callable.cpp:1126:20)
30 hermes                  hermes::vm::Callable::executeCall(hermes::vm::Handle<hermes::vm::Callable>, hermes::vm::Runtime&, hermes::vm::Handle<hermes::vm::HermesValue>, hermes::vm::Handle<hermes::vm::HermesValue>, hermes::vm::Handle<hermes::vm::JSObject>) (Callable.h:249:12)
31 hermes                  hermes::vm::functionPrototypeApply(void*, hermes::vm::Runtime&, hermes::vm::NativeArgs) (Function.cpp:224:10)
32 hermes                  hermes::vm::NativeFunction::_nativeCall(hermes::vm::NativeFunction*, hermes::vm::Runtime&) (Callable.h:503:9)
33 hermes                  hermes::vm::CallResult<hermes::vm::HermesValue, (hermes::vm::detail::CallResultSpecialize)2> hermes::vm::Interpreter::interpretFunction<false, false>(hermes::vm::Runtime&, hermes::vm::InterpreterState&) (Interpreter.cpp:287:12)
34 hermes                  hermes::vm::Runtime::interpretFunctionImpl(hermes::vm::CodeBlock*) (Interpreter.cpp:836:12)
35 hermes                  hermes::vm::JSFunction::_callImpl(hermes::vm::Handle<hermes::vm::Callable>, hermes::vm::Runtime&) (Callable.cpp:1126:20)
36 hermes                  hermes::vm::Callable::executeCall(hermes::vm::Handle<hermes::vm::Callable>, hermes::vm::Runtime&, hermes::vm::Handle<hermes::vm::HermesValue>, hermes::vm::Handle<hermes::vm::HermesValue>, hermes::vm::Handle<hermes::vm::JSObject>) (Callable.h:249:12)
37 hermes                  hermes::vm::functionPrototypeApply(void*, hermes::vm::Runtime&, hermes::vm::NativeArgs) (Function.cpp:224:10)
38 hermes                  hermes::vm::NativeFunction::_nativeCall(hermes::vm::NativeFunction*, hermes::vm::Runtime&) (Callable.h:503:9)
39 hermes                  hermes::vm::CallResult<hermes::vm::HermesValue, (hermes::vm::detail::CallResultSpecialize)2> hermes::vm::Interpreter::interpretFunction<false, false>(hermes::vm::Runtime&, hermes::vm::InterpreterState&) (Interpreter.cpp:287:12)
40 hermes                  hermes::vm::Runtime::interpretFunctionImpl(hermes::vm::CodeBlock*) (Interpreter.cpp:836:12)
41 hermes                  hermes::vm::JSFunction::_callImpl(hermes::vm::Handle<hermes::vm::Callable>, hermes::vm::Runtime&) (Callable.cpp:1126:20)
42 hermes                  hermes::vm::BoundFunction::_boundCall(hermes::vm::BoundFunction*, hermes::inst::Inst const*, hermes::vm::Runtime&) (Callable.h:249:12)
43 hermes                  hermes::vm::CallResult<hermes::vm::HermesValue, (hermes::vm::detail::CallResultSpecialize)2> hermes::vm::Interpreter::interpretFunction<false, false>(hermes::vm::Runtime&, hermes::vm::InterpreterState&) (Interpreter.cpp:291:12)
44 hermes                  hermes::vm::Runtime::interpretFunctionImpl(hermes::vm::CodeBlock*) (Interpreter.cpp:836:12)
45 hermes                  hermes::vm::JSFunction::_callImpl(hermes::vm::Handle<hermes::vm::Callable>, hermes::vm::Runtime&) (Callable.cpp:1126:20)
46 hermes                  hermes::vm::BoundFunction::_boundCall(hermes::vm::BoundFunction*, hermes::inst::Inst const*, hermes::vm::Runtime&) (Callable.h:249:12)
47 hermes                  facebook::hermes::HermesRuntimeImpl::call(facebook::jsi::Function const&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) (Callable.h:249:12)
48 driversnote             call (decorator.h:303:19)
49 driversnote             call (jsi-inl.h:234:18)
50 driversnote             operator() (function.h:505:16)
51 driversnote             operator() (function.h:505:16)
52 driversnote             tryFunc (RCTMessageThread.mm:69:20)
53 driversnote             operator() (function.h:505:16)
54 CoreFoundation          ___CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__
55 CoreFoundation          ___CFRunLoopDoBlocks
56 CoreFoundation          ___CFRunLoopRun
57 CoreFoundation          _CFRunLoopRunSpecific
58 driversnote             +[RCTCxxBridge runRunLoop] (RCTCxxBridge.mm:335:12)
59 Foundation              ___NSThread__start__
60 libsystem_pthread.dylib __pthread_start
```

**Comment by dimonnwc3** [comment]
@martinpoulsen were you able to solve it somehow? or try new update v11.2.0?

I'm having a similar issue.
Running an app in production and getting reports from users related to data loss.
Expo 47 + realm-js v11.2.0

When I try to enable hermes engine, app crashes almost on every start (9 out of 10)
So I'm running on JSC, app starts fine and I have 0 crash reports in production, but users report about silent data loss on ios, just by opening the app.

**Comment by kneth** [comment]
@dimonnwc3 Unfortunately we cannot repair corrupted files, and you will have to delete the Realm files and recreate them.

>  production, but users report about silent data loss on ios, just by opening the app.

Does this also happen for users who have only used v11.2.0?If possible, create a new issue and share stack traces.

**Comment by martinpoulsen** [comment]
@kneth I'm very happy to report that we haven't seen any new users experiencing this crash since we released our app with the Realm v. 11.2.0 upgrade.

**Comment by kneth** [comment]
@martinpoulsen What a good start of the year. Thank you for the update.

**Comment by rodrigobertolottizinsp** [comment]
@kneth how are you? 
Im still facing the issue using realm-js version 11.3.0 that uses realm core v13.1.0, it happened to two users yesterday
I reported the issue here https://github.com/realm/realm-core/issues/6207 :(
