### ISSUE TITLE
Realm crashes on hot reload in React Native

### ISSUE THREAD

**Issue by bao-multiIT** [realm/realm-js#6066]
### How frequently does the bug occur?

Always

### Description

The app crashes after 1 or 2 hot reloads with the error `Access to invalidated Results objects`, even though the code changes had nothing to do with Realm, like only changing styles and components

### Stacktrace & log output

```shell
ERROR  Error: Exception in HostFunction: Access to invalidated Results objects, js engine: hermes
Error: ENOENT: no such file or directory, open 'D:\Code\Projects\RealmHotReloadCrash\JavaScript'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at getCodeFrame (D:\Code\Projects\RealmHotReloadCrash\node_modules\metro\src\Server.js:879:18)
    at Server._symbolicate (D:\Code\Projects\RealmHotReloadCrash\node_modules\metro\src\Server.js:962:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Server._processRequest (D:\Code\Projects\RealmHotReloadCrash\node_modules\metro\src\Server.js:418:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'D:\\Code\\Projects\\RealmHotReloadCrash\\JavaScript'
}
```

### Can you reproduce the bug?

Always

### Reproduction Steps

1. Pull [my repo](https://github.com/bao-multiIT/realm-hot-reload-crash)
2. Start the development environment with `yarn start` and `yarn android`
3. Open the app on your phone
4. Open the project in any editor
5. Now make any changes to the code, for example changing some values in the styles, like 'black' to 'red'
6. Hit save, the hot reload will occur
7. The app will crash and the error will appear in the terminal
8. If it doesn't crash, then just make some more changes and save again, it will eventually happen, most of the time it took me 1 save to crash but sometimes it takes 2 saves

### Version

^11.9.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android 13.0.3

### Build environment

I built the app in Windows 10, connected to physical phone through USB debugging to install and debug the app

**Comment by bao-multiIT** [comment]
Maybe related to https://github.com/realm/realm-js/issues/4746, maybe Realm automatically closes on hot reload and causes the previous query results to be invalidated?

**Comment by Acetyld** [comment]
Can you show some code?

**Comment by bao-multiIT** [comment]
> Can you show some code?

Hi, sorry I forgot, attached my repo to the Reproduction steps

**Comment by bao-multiIT** [comment]
Wasn't anything special, just beginner code from the Realm React Native guide with some small changes, surely it's not the cause of the problem, i can change it into anything Realm related and still reproduce this bug

**Comment by kneth** [comment]
In v12.0.0-rc.2 we fixed https://github.com/realm/realm-js/issues/5904 which might be related (reloading a RN app during development). I believe the defect was introduced in v11.7.0. Can you try to upgrade and see if it solves the issue?

**Comment by bao-multiIT** [comment]
hi @kneth, i just tried with 12.0.0-rc.2, had to install peer dependency bson^5.4.0 too
the same error is still happening:
```
 ERROR  Error: Access to invalidated Results objects, js engine: hermes
```

there's also a warning when i run the app:
```
 WARN  BSON: For React Native please polyfill crypto.getRandomValues, e.g. using: https://www.npmjs.com/package/react-native-get-random-values.
```

**Comment by kneth** [comment]
@bao-multiIT Thank you for the update. We need to investigate to understand the root cause.

**Comment by takameyer** [comment]
@bao-multiIT I just tried out your repo and it does indeed crash and I can explain why.  It is due to how React re-renders modules with fast-refresh.  If you have a module (file) which contains two components, one of which is the child of the other (like your example), changing the child will also cause the parent to re-render.  In your example, the `App` contains the `RealmProvider`.  When this is re-rendered the `realm` within the Provider is closed and re-opened.  This has the unfortunate side-effect of invalidating the `profiles` that have been returned from `useQuery`.  This can be proven by setting the flag `closeOnUnmount` to `false` on the `RealmProvider`.
This can, however, be fixed by separating your component containing Providers (typically named `AppWrapper`) and the children into separate modules (or files).  Let us know if that helps.
