### ISSUE TITLE
Collection Notifications not working in chrome debug mode

### ISSUE THREAD

**Issue by rpereira** [realm/realm-js#686]
Hi, @alazier 

I've been experimenting with this library and I can't get Collection Notifications to work. Here's what I have so far.

```js
// models/Entry.js
import Realm from 'realm';

class Entry extends Realm.Object {}
Entry.schema = {
  name: 'Entry',
  primaryKey: 'id',
  properties: {
    name: 'string',
    id: 'int',
    timestamp: 'date'
  }
};

export default Entry;
```

```js
// models/RealmSchemaManager.js
import Realm from 'realm';
import Entry from './Entry';
...

export default new Realm({ schema: [Entry, ...] });
```

```js
// containers/Entries.js
import realm from '../models/RealmSchemaManager'
...

class Entries extends React.Component {
  componentDidMount() {
    this.entries().addListener((entries, changed) => {
      console.log('entries changed');
    });
  }

  entries() {
    return realm.objects('Entry').sorted(...).filtered(...);
  }
  ...
}
```
Error:
`this.entries(...).addListener is not a function`. I really don't get this. It seems to be correct, as per the documentation. I'm running the latest version of this lib.

Thanks.

**Comment by alazier** [comment]
Your code is correct. There is a bug with collection notifications when using chrome debug mode. I just pushed a partial fix for this in `0.15.1-rc`. This should at least avoid the error you encountering although more work will likely need to be done to make collection notifications work correctly in chrome debug mode. Everything should work properly when not using the debugger - if this is not the case please let us know!

**Comment by rpereira** [comment]
I'm not using chrome debug mode @alazier. I've also installed `0.15.1-rc` and the problem persists.

**Comment by rpereira** [comment]
Turns out I had a bug in my code. I wrote `entries = () =>` instead of `entries()`. Version `0.15.1-rc` fixed this issue. 

Thanks for your time. I'm going to close this now.
