### ISSUE TITLE
Electron and sandboxing on macOS

### ISSUE THREAD

**Issue by stel** [realm/realm-js#818]
Bindings should handle if it's build for using in Electron app and use the system API to get writable directories for any internal data in sandbox.

Right now `realm-object-server` is created in the working directory that crashes the app.

**Comment by Ted-Mohamed** [comment]
Just wanted to mention that changing the working directory before requiring realm the app will work.
```javascript
process.chdir('/directory/outside/app/folder')
const realm = new require('realm')
```

**Comment by blagoev** [comment]
@Ted-Mohamed process.chdir will not have effect on the require if it is written like that. 
Check the module require high-level algorithm here:
https://nodejs.org/api/modules.html#modules_all_together

**Comment by Ted-Mohamed** [comment]
@blagoev it's okay, english is not my native language. Sorry I was not so clear. I edited my comment.

**Comment by adeperio** [comment]
+1 for this feature! We are releasing an offline first desktop app in April so hanging out for this!

**Comment by kraenhansen** [comment]
@kneth is there a way through the Realm JS API to choose where the `realm-object-server` data is stored?

**Comment by kneth** [comment]
@kraenhansen Currently, no. `realm-object-server` is fixed and it location is specific to the platform (Android, iOS, Node.js).

**Comment by vazra** [comment]
for those who are still facing this issue, you can set db path in path the [configuration](https://realm.io/docs/javascript/latest/api/Realm.html#~Configuration) you are passing while opening realm connection.  
you can get the user home path in electron with, and create new db path
```
const remote = require("electron").remote;
const dbpath = path.join(
  app.getPath("home"),
  "data.realm"
);
```
add the new db path to the config options.

eg: 
```typescript
const dbConfig: Realm.Configuration = {
  schema: [Person],
  deleteRealmIfMigrationNeeded: true,
  path: dbpath,
  // path: "./.db/shdb/data.realm",
};
```

then the db will be created in home dir, in the specified location . hope this helps.

**Comment by Abhishekmatta** [comment]
> for those who are still facing this issue, you can set db path in path the [configuration](https://realm.io/docs/javascript/latest/api/Realm.html#~Configuration) you are passing while opening realm connection.
> you can get the user home path in electron with, and create new db path
> 
> ```
> const remote = require("electron").remote;
> const dbpath = path.join(
>   app.getPath("home"),
>   "data.realm"
> );
> ```
> 
> add the new db path to the config options.
> 
> eg:
> 
> ```ts
> const dbConfig: Realm.Configuration = {
>   schema: [Person],
>   deleteRealmIfMigrationNeeded: true,
>   path: dbpath,
>   // path: "./.db/shdb/data.realm",
> };
> ```
> 
> then the db will be created in home dir, in the specified location . hope this helps.

As there are no official support/docs for the realm to be included in the electron as local DB, Can you please tell me what is the best approach to be followed i.e include it in main or renderer?
2. Is it possible to sync the realm DB with MongoDB when it is connected to the internet by following your approach?

**Comment by ianpward** [comment]
there is an electron quickstart here - 
https://docs.mongodb.com/realm/node/electron

**Comment by abhishekmatta999** [comment]
> for those who are still facing this issue, you can set db path in path the [configuration](https://realm.io/docs/javascript/latest/api/Realm.html#~Configuration) you are passing while opening realm connection.
> you can get the user home path in electron with, and create new db path
> 
> ```
> const remote = require("electron").remote;
> const dbpath = path.join(
>   app.getPath("home"),
>   "data.realm"
> );
> ```
> 
> add the new db path to the config options.
> 
> eg:
> 
> ```ts
> const dbConfig: Realm.Configuration = {
>   schema: [Person],
>   deleteRealmIfMigrationNeeded: true,
>   path: dbpath,
>   // path: "./.db/shdb/data.realm",
> };
> ```
> 
> then the db will be created in home dir, in the specified location . hope this helps.

This is not working. It's giving me error: `Uncaught Error: make_dir() failed: Read-only file system Path: /mongodb-realm/`

**Comment by kneth** [comment]
@abhishekmatta999 Your error message indicates that the path is pointing to a place on your file system where you cannot create files. Please verify that `app.getPath("home")` produce a reasonable path.
